import AppKit

/// 剪贴板：去掉格式、清空。
/// 只在你点按钮或按快捷键的那一刻读一次剪贴板，平时不监视、不保存、也不记录任何内容。
enum Clipboard {
    /// 密码管理器等应用会给敏感内容加上这些标记，告诉剪贴板工具「不要记录」；转换时原样保留
    private static let markerTypes = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// 把剪贴板里的文字换成不带格式的纯文字。返回文字的字数，剪贴板里没有文字时返回 nil
    static func makePlainText() -> Int? {
        let pasteboard = NSPasteboard.general
        guard let text = pasteboard.string(forType: .string) else { return nil }
        let existing = pasteboard.types ?? []
        let markers = markerTypes.filter { existing.contains($0) }

        pasteboard.declareTypes([.string] + markers, owner: nil)
        pasteboard.setString(text, forType: .string)
        for marker in markers {
            pasteboard.setData(Data(), forType: marker)
        }
        return text.count
    }

    /// 清空剪贴板（例如复制过密码之后）
    static func clear() {
        NSPasteboard.general.clearContents()
    }
}
